#!/usr/bin/expect -f

puts "Starting the installer..."
spawn /opt/sms/sms_install/install.sh

expect "O SMS Power View  utilizará o JAVA instalado em:/opt/java/jre"

expect "Informe o valor da variável DISPLAY. Pressione <ENTER> para assumir valor default"
send ":0.0\r"

expect "Informe o diretorio de instalacao do powerview"
send "\r"

expect "Configurar SMS POWERVIEW LINUX em /opt/powerview (s/n)?"
send "s\r"

expect eof

puts "Installer finished."
